DELETE FROM user_roles WHERE TRUE;

DELETE FROM artist_subscribers WHERE TRUE;
DELETE FROM user_subscriptions WHERE TRUE;

DELETE FROM artists WHERE TRUE;

DELETE FROM subscriber WHERE TRUE;


DELETE FROM users WHERE TRUE;

